server:
  port: 8088

logging:
  level:
    root: INFO
    # org.spiderflow: DEBUG

spider:
  thread:
    max: 64
    default: 8
  job:
    enable: false
  workspace: ${user.dir}/spider-data
  bloomfilter:
    capacity: 1000000
    error-rate: 0.0001
  # detect:
  #   dead-cycle: 5000
  notice:
    subject: spider-flow流程通知
    content:
      start: 流程开始执行：{name}，开始时间：{currentDate}
      end: 流程执行完毕：{name}，结束时间：{currentDate}
      exception: 流程发生异常：{name}，异常时间：{currentDate}

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail_on_empty_beans: false
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spiderflow?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
  mail:
    host: smtp.qq.com
    port: 465
    username: test@qq.com
    password: test
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

# selenium 插件配置
selenium:
  driver:
    chrome: E:/driver/chromedriver.exe
    firefox: E:/driver/geckodriver.exe